import React from "react";
import { Page, View, Text } from "@react-pdf/renderer";
import { colors } from "../styles";
import type { ClaudeAnalysis } from "@/types/analysis";

interface Props {
  address: string;
  clientName: string;
  inspectorName: string;
  inspectionDate: string;
  analysis: ClaudeAnalysis;
}

export function CoverSection({ address, clientName, inspectorName, inspectionDate, analysis }: Props) {
  const specs = analysis.system_specs;
  const panelCount = specs?.module_count;
  const panelWatts = specs?.module_watts;
  const panelBrand = specs?.module_brand;
  const inverterCount = specs?.inverter_count;
  const inverterKw = specs?.inverter_kw;

  return (
    <Page size="LETTER" style={{ fontFamily: "Helvetica", backgroundColor: colors.primary }}>
      {/* Header bar */}
      <View style={{ backgroundColor: colors.accent, padding: "16 40 16 40" }}>
        <Text style={{ fontSize: 10, color: "#ffffff", fontFamily: "Helvetica-Bold", letterSpacing: 2 }}>
          SOLAR INSTALLATION INSPECTION
        </Text>
      </View>

      {/* Main content */}
      <View style={{ padding: "50 40 40 40", flex: 1 }}>
        <Text style={{ fontSize: 28, fontFamily: "Helvetica-Bold", color: "#ffffff", marginBottom: 8 }}>
          Inspection Report
        </Text>
        <Text style={{ fontSize: 14, color: "#94a3b8", marginBottom: 40 }}>
          {address || "Solar Installation"}
        </Text>

        {/* Info grid */}
        <View style={{ backgroundColor: "rgba(255,255,255,0.08)", borderRadius: 8, padding: 20, marginBottom: 30 }}>
          {clientName ? (
            <View style={{ marginBottom: 14 }}>
              <Text style={{ fontSize: 8, color: "#94a3b8", letterSpacing: 1, marginBottom: 3 }}>CLIENT</Text>
              <Text style={{ fontSize: 13, color: "#ffffff", fontFamily: "Helvetica-Bold" }}>{clientName}</Text>
            </View>
          ) : null}
          {address ? (
            <View style={{ marginBottom: 14 }}>
              <Text style={{ fontSize: 8, color: "#94a3b8", letterSpacing: 1, marginBottom: 3 }}>PROPERTY ADDRESS</Text>
              <Text style={{ fontSize: 12, color: "#e2e8f0" }}>{address}</Text>
            </View>
          ) : null}
          <View style={{ flexDirection: "row", gap: 40 }}>
            {inspectionDate ? (
              <View>
                <Text style={{ fontSize: 8, color: "#94a3b8", letterSpacing: 1, marginBottom: 3 }}>INSPECTION DATE</Text>
                <Text style={{ fontSize: 11, color: "#e2e8f0" }}>{inspectionDate}</Text>
              </View>
            ) : null}
            {inspectorName ? (
              <View>
                <Text style={{ fontSize: 8, color: "#94a3b8", letterSpacing: 1, marginBottom: 3 }}>INSPECTOR</Text>
                <Text style={{ fontSize: 11, color: "#e2e8f0" }}>{inspectorName}</Text>
              </View>
            ) : null}
          </View>
        </View>

        {/* System summary */}
        {(panelCount || inverterCount) ? (
          <View style={{ backgroundColor: colors.accent, borderRadius: 8, padding: 16 }}>
            <Text style={{ fontSize: 9, color: "#ffffff", fontFamily: "Helvetica-Bold", marginBottom: 10, letterSpacing: 1 }}>
              SYSTEM SUMMARY
            </Text>
            <View style={{ flexDirection: "row", gap: 30 }}>
              {panelCount ? (
                <View>
                  <Text style={{ fontSize: 20, fontFamily: "Helvetica-Bold", color: "#ffffff" }}>{String(panelCount)}</Text>
                  <Text style={{ fontSize: 9, color: "rgba(255,255,255,0.8)" }}>
                    {panelBrand ? `${panelBrand} Panels` : "Panels"}
                    {panelWatts ? ` · ${panelWatts}W each` : ""}
                  </Text>
                </View>
              ) : null}
              {inverterCount ? (
                <View>
                  <Text style={{ fontSize: 20, fontFamily: "Helvetica-Bold", color: "#ffffff" }}>{String(inverterCount)}</Text>
                  <Text style={{ fontSize: 9, color: "rgba(255,255,255,0.8)" }}>
                    {`Inverter${Number(inverterCount) !== 1 ? "s" : ""}`}
                    {inverterKw ? ` · ${inverterKw} kW` : ""}
                  </Text>
                </View>
              ) : null}
            </View>
          </View>
        ) : null}
      </View>

      {/* Footer */}
      <View style={{ padding: "16 40", borderTopWidth: 1, borderTopColor: "rgba(255,255,255,0.15)" }}>
        <Text style={{ fontSize: 8, color: "#64748b" }}>
          Generated by Solar Inspector · All data extracted from provided photos only
        </Text>
      </View>
    </Page>
  );
}
